import { StyleSheet } from 'react-native';
import Constants from 'expo-constants';

export default styles = 

StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: '20%',
    backgroundColor: '#282832',
  },
  title: {
    marginTop: '30%',
    marginBottom: '10%',
    fontSize: 48,
    //fontWeight: 'bold',
    textAlign: 'center',
    color: '#c6d6d6',
    //fontFamily: Inter_700Bold,
  },
  botaoCalcular: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: '70%',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 500,
    elevation: 3,
    backgroundColor: '#a92727',
    marginTop: '30%',
    height: 60,
  },
  textoBotao: {
    fontWeight: 'bold',
    letterSpacing: 1,
    color: '#c6d6d6',
  },
  botaoResultado: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderRadius: 4,
    elevation: 3,
    marginTop: 10,
    height: 60,
  },
  bt: {
    backgroundColor: '#dee7e7',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  botaoOutro: {
    height: '170%',
    width: '25%',
    justifyContent: 'center',
    backgroundColor: '#77181e',
    alignSelf: 'center',
    alignItems: 'center',
  },
  title2: {
    marginBottom: '10%',
    fontSize: 48,
    //fontWeight: 'bold',
    textAlign: 'center',
    color: '#c6d6d6',
  },
  Img: {
    height: '30%',
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  Text: {
    marginTop: 12,
    padding: 50,
    borderRadius: 8,
    color: '#282832',
    backgroundColor: '#dee7e7',
    width: '90%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  container2: {
    flex: 1,
    paddingTop: '5%',
    backgroundColor: '#282832',
  },
  container3: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#282832',
    //padding: 8,
  },
  content: {
    padding: 8,
  },
  title3: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#c6d6d6',
     justifyContent: 'center',
  },
  input: {
    color: '#c6d6d6',
    fontSize: 18,
    height: 60,
    padding: 10,
    justifyContent: 'center',
    textAlign: 'center',
  },
  viewInput: {
    borderWidth: 1,
    height: 60,
    color:'#282832',
  },
  botaoCalcular2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: '#a92727',
    marginTop: 10,
    height: 60,
  },
  botaoResultado2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: '#dee7e7',
    marginTop: 10,
    height: 60,
  },
  textoBotao2: {
    color: '#282832',
    fontSize: 18,
    fontWeight: 'bold',
  },
  Text2: {
    margin: 24,
    fontSize: 18,
    color: '#282832',
    fontWeight: 'bold',
    textAlign: 'center',
  },
   Img3: {
    height: '50%',
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  Text3: {
    marginTop: 12,
    padding: 35,
    borderRadius: 8,
    color: '#282832',
    backgroundColor: '#dee7e7',
    width: '90%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
});
